[workspace]
authors = ["nichmor <nmorkotilo@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "pixi_build_git"
platforms = ["osx-arm64"]
preview = ['pixi-build']
version = "0.1.0"

[tasks]

[dependencies]
# boltons = { path = "." }
# boltons = "*"
boltons = "*"
# boost-check = { git = "ssh://git@github.com/nichmor/pixi-build-examples", branch = "feat/graf-channel", subdirectory = "boost-check" }
boost-check = { git = "https://github.com/nichmor/pixi-build-examples", branch = "fix-backend" }

