[project]
dependencies = ["flask==2.*"]
description = "Example how to get started with flask in a pixi environment."
name = "flask-hello-world-pyproject"
readme = "README.md"
requires-python = ">=3.11"
version = "0.1.0"

[project.optional-dependencies]
test = ["pytest"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.pixi.project]
channels = ["conda-forge"]
platforms = ["linux-64", "osx-arm64", "osx-64", "win-64"]

[tool.pixi.pypi-dependencies]
flask-hello-world-pyproject = { path = ".", editable = true }

[tool.pixi.dependencies]
# flask = "2.*"
flask-hello-world-pyproject = { path = "." }


[tool.pixi.environments]
default = { solve-group = "default" }
test = { features = ["test"], solve-group = "default" }

[tool.pixi.tasks]
start = "python -m flask --app flask_hello_world_pyproject.app:app run --port=5050"

[tool.pixi.feature.test.tasks]
test = "pytest -v tests/*"

[tool.pixi.host-dependencies]
hatchling = "*"


[tool.pixi.build]
build-backend = "pixi-build-python"
channels = [
  "https://repo.prefix.dev/graf",
  "https://fast.prefix.dev/conda-forge",
]
dependencies = ["pixi-build-python"]
